In [3]:
import numpy as np

i = np.array([[10, 20, 30], [40, 50, 60], [70,80,90]])

for j in i:
    for k in j:
        print(k)

10
20
30
40
50
60
70
80
90


In [4]:
import numpy as np

i = np.array([
    [[10, 20, 30], [40, 50, 60], [70,80,90]],
    [[1, 2, 3], [4, 5, 6], [7,8,9]],
    [[10, 20, 30], [40, 50, 60], [70,80,90]],
 ])

for j in i:
    print(j)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [7]:
import numpy as np

i = np.array([
    [[10, 20, 30], [40, 50, 60], [70,80,90]],
    [[1, 2, 3], [4, 5, 6], [7,8,9]],
    [[10, 20, 30], [40, 50, 60], [70,80,90]],
 ])

for j in i:
    for k in j:
        for m in k:
            print(m)

10
20
30
40
50
60
70
80
90
1
2
3
4
5
6
7
8
9
10
20
30
40
50
60
70
80
90


In [8]:
from numpy import random

i = random.randint(10)

print(i)

2


In [9]:
from numpy import random

i = random.rand()

print(i)

0.2217347233842757


In [10]:
from numpy import random

i = random.rand(11)

print(i)

[0.02794022 0.2778216  0.02457154 0.37808913 0.46629198 0.16004229
 0.29518384 0.06795197 0.97990291 0.11998573 0.61816281]


In [11]:
from numpy import random

i = random.randint(100, size=(10))

print(i)

[25 16 62 48 60 78 82 34 30 71]


In [12]:
from numpy import random

i = random.randint(100, size=(3, 5))

print(i)

[[91 63 25 74 65]
 [ 6  4 79 24 19]
 [61  7 83 60 26]]


In [13]:
from numpy import random

i = random.randint(100, size=(5, 5))

print(i)

[[16 98 40 41 91]
 [63 15 51 89 81]
 [72 48 72 29 36]
 [56 87 16 70 53]
 [18 85 86 52 89]]


In [15]:
from numpy import random

i = random.randint(100, size=(3,5,2))

print(i)

[[[14  9]
  [78  0]
  [ 9 42]
  [51 85]
  [58 11]]

 [[70 83]
  [76 97]
  [53 73]
  [90 12]
  [33 49]]

 [[83 32]
  [80 92]
  [65 17]
  [18 56]
  [58 44]]]


In [16]:
from numpy import random

i = random.rand(3, 5)

print(i)

[[0.09961459 0.76270551 0.64461611 0.11060839 0.8325768 ]
 [0.81495235 0.29025858 0.51049021 0.17576209 0.22523268]
 [0.12320006 0.48068556 0.477561   0.88839552 0.9442285 ]]


In [17]:
from numpy import random

list1 = [10,20,30,40,50,60,70,80,90]

i = random.choice(list1)

print(i)

70


In [18]:
from numpy import random

list1 = [10,20,30,40,50,60,70]

i = random.choice(list1, size=(3, 5))

print(i)

[[10 60 20 10 30]
 [60 10 30 10 20]
 [20 30 60 70 30]]


In [19]:
from numpy import random

list1 = [10,20,30,40,50,60,70]

i = random.choice(list1, size=(3, 5, 2))

print(i)

[[[40 20]
  [20 60]
  [60 50]
  [30 20]
  [10 40]]

 [[50 60]
  [20 20]
  [70 20]
  [50 10]
  [30 10]]

 [[50 70]
  [70 10]
  [20 30]
  [50 20]
  [20 40]]]
